### ISSUE TITLE
Can't build via npm on node version >= 0.12.2

### ISSUE THREAD

**Issue by mgostisha** [k0sukey/alloy-smelter#9]
There's a problem with the base64 package used by alloy-smelter that causes the build to fail on node versions >= 0.12.2 when trying the command node-gyp rebuild

**Comment by anthonyjesmok** [comment]
I'm having this issue as well. Here's part of my error dump. I really hope someone can fix this.

```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/base64/base64.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/alloy-smelter/node_modules/base64
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "alloy-smelter"
npm ERR! node v0.12.4
npm ERR! npm  v2.13.4
npm ERR! code ELIFECYCLE

npm ERR! base64@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the base64@2.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the base64 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls base64
npm ERR! There is likely additional logging output above.
```

**Comment by mgostisha** [comment]
@anthonyjesmok I finally forked the repo and made the change so it works on node versions > 0.10.x. Feel free to install it! https://github.com/mgostisha/alloy-smelter

**Comment by anthonyjesmok** [comment]
Thanks @mgostisha, I will definitely be using it! Glad to see you were able to fix it.
